openapi: 3.0.0
info:
  title: MedicalPlus API
  description: API for user authentication and management
  version: 1.0.0

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    AuthResponse:
      type: object
      required: [accessToken, user]
      properties:
        accessToken:
          type: string
        user:
          $ref: "#/components/schemas/User"

    ErrorResponse:
      type: object
      required: [code, message]
      properties:
        code:
          type: string
        message:
          type: string
        details:
          type: object
          nullable: true

    LoginRequest:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password

    RegisterRequest:
      type: object
      required: [email, password, name]
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
          minLength: 8
        name:
          type: string
          minLength: 2

    UserRole:
      type: string
      enum: [patient, doctor, admin]

    ChangeRoleRequest:
      type: object
      required: [role]
      properties:
        role:
          $ref: "#/components/schemas/UserRole"
        doctorData:
          type: object
          nullable: true
          description: "Обязательно, если role == 'doctor'"
          properties:
            specialization:
              type: string
            licenseNumber:
              type: string
            experience:
              type: integer
            bio:
              type: string
            education:
              type: string

    User:
      type: object
      required: [id, email, role, name]
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        name:
          type: string
        role:
          $ref: "#/components/schemas/UserRole"

    Doctor:
      type: object
      required:
        [
          id,
          userId,
          specialization,
          licenseNumber,
          experience,
          isActive,
          name,
          email,
        ]
      properties:
        id:
          type: string
          format: uuid
        userId:
          type: string
          format: uuid
          description: Ссылка на User
        name:
          type: string
          description: Имя врача из профиля User
        email:
          type: string
          format: email
          description: Email врача из профиля User
        specialization:
          type: string
          example: "Кардиолог"
        licenseNumber:
          type: string
          example: "MD-12345"
        experience:
          type: integer
          minimum: 0
          description: Количество лет опыта
        bio:
          type: string
          description: Биография врача
        education:
          type: string
          description: Образование
        rating:
          type: number
          format: float
          minimum: 0
          maximum: 5
        isActive:
          type: boolean
          description: Активен ли врач для записи
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    AppointmentRequest:
      type: object
      required: [date, time, status]
      properties:
        date:
          type: string
        time:
          type: string
        status:
          type: string
          enum:
            - available
            - booked
            - cancelled

    Appointment:
      type: object
      required:
        - id
        - doctorId
        - date
        - time
        - status
        - createdAt
      properties:
        id:
          type: string
          format: uuid

        doctorId:
          type: string

        date:
          type: string
          format: date

        time:
          type: string

        status:
          type: string
          enum:
            - available
            - booked
            - cancelled
        patientId:
          type: string
          nullable: true
        patientName:
          type: string
          nullable: true
        createdAt:
          type: string
          format: date-time

security:
  - bearerAuth: []

paths:
  /doctors:
    get:
      summary: Получение списка всех врачей
      description: Возвращает массив всех активных врачей. Доступно без авторизации.
      tags:
        - Doctors
      responses:
        "200":
          description: Список врачей успешно получен
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Doctor"
        "500":
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /doctors/{id}/appointments:
    patch:
      summary: Забронировать существующий слот
      tags:
        - Appointments
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
          description: ID врача
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - appointmentId
              properties:
                appointmentId:
                  type: string
                  format: uuid
                  description: ID записи (слота), которую нужно забронировать
      responses:
        "200":
          description: Слот успешно забронирован
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Appointment"
        "400":
          description: Слот уже забронирован или не принадлежит данному врачу
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Не авторизован
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Врач или запись не найдены
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

    get:
      summary: Получение доступных записей
      description: Возвращает доступных записей
      tags:
        - Appointments
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          required: true
          description: ID врача
      responses:
        "200":
          description: Записи найдены
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Appointment"
        "404":
          description: Врач не найден
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /doctors/{id}:
    get:
      summary: Получение данных конкретного врача
      description: Возвращает полную информацию о враче по его уникальному ID. Доступно без авторизации.
      tags:
        - Doctors
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          required: true
          description: ID врача (не userId, а именно Doctor ID)
      responses:
        "200":
          description: Данные врача найдены
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Doctor"
        "404":
          description: Врач не найден
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /admin/users:
    get:
      summary: Получение списка всех пользователей (только для Admin)
      security:
        - bearerAuth: []
      tags:
        - Users
      responses:
        "200":
          description: Список пользователей успешно получен
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
        "401":
          description: Не авторизован (отсутствует токен)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: Доступ запрещен (недостаточно прав)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /admin/users/{id}/role:
    patch:
      summary: Изменение роли пользователя (только для Admin)
      security:
        - bearerAuth: []
      tags:
        - Users
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          required: true
          description: ID пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ChangeRoleRequest"
      responses:
        "200":
          description: Роль успешно обновлена
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "404":
          description: Пользователь не найден
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

        "400":
          description: Некорректные данные (например, неверная роль)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: Доступ запрещен (недостаточно прав)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /auth/login:
    post:
      summary: Аутентификация пользователя (Вход)
      tags: [Auth]
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: Успешный вход
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthResponse"
        "401":
          description: Неверные учетные данные
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /auth/register:
    post:
      summary: Регистрация нового пациента
      tags: [Auth]
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterRequest"
      responses:
        "201":
          description: Пользователь создан
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthResponse"
        "400":
          description: Ошибка валидации
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "409":
          description: Email уже занят
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /auth/me:
    get:
      summary: Получение профиля текущего пользователя
      tags: [Auth]
      responses:
        "200":
          description: Профиль пользователя
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "401":
          description: Токен невалиден
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /auth/refresh:
    post:
      summary: Обновление Access Token
      tags: [Auth]
      security: []
      parameters:
        - in: cookie
          name: refreshToken
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Токен обновлён
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthResponse"
        "401":
          description: Refresh Token невалиден
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /my/appointments:
    get:
      summary: Получение записей текущего пользователя
      description: Возвращает список всех записей, где текущий пользователь является пациентом (статус не 'available').
      tags:
        - Appointments
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Список записей успешно получен
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Appointment"
        "401":
          description: Пользователь не авторизован
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /doctor/appointments:
    get:
      summary: Get doctor appointments
      description: Returns a list of all appointments (slots) for the doctor.
      tags:
        - Doctor
      security:
        - bearerAuth: []

      responses:
        "200":
          description: A list of appointments successfully retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Appointment"

        "400":
          description: Некорректные данные
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

        "403":
          description: Доступ запрещен (недостаточно прав)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

        "404":
          description: Пользователь не найден
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    post:
      summary: Create appointment slots by doctor
      description: Doctor creates available appointment slots for a specific date
      tags:
        - Doctor
      security:
        - bearerAuth: []

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: "#/components/schemas/AppointmentRequest"

      responses:
        "200":
          description: Appointment slots successfully created
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Appointment"

        "404":
          description: Пользователь не найден
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

        "400":
          description: Некорректные данные
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

        "403":
          description: Доступ запрещен (недостаточно прав)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
